services:
  task-manager-api:
    container_name: task-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    network_mode: host
