### List tasks
GET http://localhost:8080/api/v1/tasks?Page=1&PageSize=10
Content-Type: application/json

### Create Task
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json

{
  "title": "task add test - title",
  "description": "task add test - description"
}

### Get Task
GET http://localhost:8080/api/v1/tasks/0190d157-933c-78ed-a33d-76f5e4f5b97a
Content-Type: application/json

### Delete Task
DELETE  http://localhost:8080/api/v1/tasks/0190d157-933c-78ed-a33d-76f5e4f5b97a
Content-Type: application/json
