definitions:
  models.CreateTaskRequest:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - description
    - title
    type: object
  task.Task:
    properties:
      completionDate:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: string
      isCompleted:
        type: boolean
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API documentation.
  title: REST API
  version: "1.0"
paths:
  /api/v1/tasks:
    get:
      consumes:
      - application/json
      description: Returns list of the created tasks
      parameters:
      - description: Page to retrieve
        in: query
        name: Page
        required: true
        type: integer
      - description: Items per page
        in: query
        name: PageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/task.Task'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: List Tasks
    post:
      consumes:
      - application/json
      description: Creates new task
      parameters:
      - description: title and description for the new task
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/models.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/task.Task'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Create Task
  /api/v1/tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes the task with given id
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Delete Task
    get:
      consumes:
      - application/json
      description: Returns the task with given id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/task.Task'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Get Task
  /api/v1/users:
    get:
      responses: {}
      summary: Login user
  /api/v1/users/login:
    post:
      responses: {}
      summary: Login user
  /api/v1/users/register:
    post:
      responses: {}
      summary: Registers user
swagger: "2.0"
